In [3]:
"""
ocr Hello World.

英文字母识别
"""
print("hello")

hello


In [4]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [7]:
# Load the data, converters convert the letter to a number
data= np.loadtxt('letter-recognition.data', dtype= 'float32', delimiter = ',', converters= {0: lambda ch: ord(ch)-ord('A')})
data

array([[19.,  2.,  8., ...,  8.,  0.,  8.],
       [ 8.,  5., 12., ...,  8.,  4., 10.],
       [ 3.,  4., 11., ...,  7.,  3.,  9.],
       ...,
       [19.,  6.,  9., ..., 12.,  2.,  4.],
       [18.,  2.,  3., ...,  9.,  5.,  8.],
       [ 0.,  4.,  9., ...,  7.,  2.,  8.]], dtype=float32)

In [15]:
# split the data to two, 10000 each for train and test 
train, test = np.vsplit(data,2)

# split trainData and testData to features and responses
responses, trainData = np.hsplit(train,[1])
labels, testData = np.hsplit(test,[1])

In [22]:
# Initiate the kNN, classify, measure accuracy.
#knn = cv2.KNearest()
knn = cv2.ml.KNearest_create()
print(trainData)
#knn.train(trainData, responses)
knn.train(trainData, cv2.ml.ROW_SAMPLE, responses)
ret, result, neighbours, dist = knn.findNearest(testData, k=5)

[[ 2.  8.  3. ...  8.  0.  8.]
 [ 5. 12.  3. ...  8.  4. 10.]
 [ 4. 11.  6. ...  7.  3.  9.]
 ...
 [ 5. 11.  7. ...  7.  0.  7.]
 [ 4.  9.  6. ... 11.  3.  9.]
 [ 5. 10.  7. ...  8.  4.  8.]]


In [23]:
correct = np.count_nonzero(result == labels)
accuracy = correct*100.0/10000
print(accuracy)

93.06
